### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by mredaelli** [eno-lang/enolib#6] opened 2019-05-02 17:33 UTC
I'm trying to build the package and run the tests, but I get many failures in the `analizer` folder.

For instance:
```
________________________________ test_tokenizer ________________________________

    def test_tokenizer():
        analysis = analyze(input)

>       assert analysis == snapshot(analysis, 'tests/analyzer/snapshots/analyzer.snap.yaml')
E       AssertionError: assert 'document: &i...8\nmeta: []\n' == 'document: &id...8\nmeta: []\n'
E         Skipping 118 identical leading characters in diff, use -v to show
E         - thon/tuple [8, 9]
E         ?           -------
E         + thon/tuple
E         +       - 8
E         +       - 9
E         -       key: !!python/tuple [0, 8]...
E
E         ...Full output truncated (275 lines hidden), use '-vv' to show

tests/analyzer/test_analyzer.py:28: AssertionError
```

Is it me?

**Comment by simonrepp** [comment] 2019-05-03 10:32
Hey, thanks for reporting this!

enolib is prominently using snapshot tests and it looks to me as if the issue here is that the yaml string serialization stored in the snapshot was not deterministically reproduced when you ran the tests. Maybe one of us is using a different version of pyyaml than the other or the string dumps that pyyaml produces are just generally not guaranteed to be deterministic e.g. across different platforms ...

A viable option to fix this would be to compare the again-deserialized python dict representations instead of the raw string dumps (which would be generally more sensible anway), though I have a vague recollection that there was a reason I'm not doing this, something like pytest's diffs of complex python dicts being so unusable that I wanted to rather have string dumps that I can externally compare with https://meldmerge.org/ instead.

If you want to look into this let me know (`tests/util.py` and `tests/analyzer/util.py` are of relevance for fixing this) otherwise I'll see if I get to look into it later today or the next days sometime. :)

**Comment by simonrepp** [comment] 2019-05-03 11:50
I investigated some more and it turns out I remembered wrong - the reason for comparing the string serialization (instead of the actual deserialized objects) was that pytest apparently does not support asserting equality of python objects with circular references (which I have in almost all tests):

```
    def test_continuations():
        analysis = analyze(input)
    
>       assert analysis == snapshot(analysis, 'tests/analyzer/snapshots/continuations.snap.yaml')
E       RecursionError: maximum recursion depth exceeded in comparison

tests/analyzer/test_continuations.py:37: RecursionError
```

json isn't an option either because it can not even encode circular references:

```
    def _iterencode_dict(dct, _current_indent_level):
        if not dct:
            yield '{}'
            return
        if markers is not None:
            markerid = id(dct)
            if markerid in markers:
>               raise ValueError("Circular reference detected")
E               ValueError: Circular reference detected

/usr/lib/python3.7/json/encoder.py:340: ValueError
```

I'm a little short on good ideas right now, do you have any suggestions how we could resolve this conundrum?

Most favorable course of action to me would be to somehow teach pytest to compare objects with circular references, maybe this is in fact easy to enable/work around and I'm just missing the obvious? :)

Alternatively we could also try to get the yaml string serializations deterministic, not particularly excited to go that road though, so I'd be happy about other suggestions!

**Comment by mredaelli** [comment] 2019-05-03 11:53
Thanks for the quick feedback! I will defitely take a look, although I can hardly promise anything :)

**Comment by mredaelli** [comment] 2019-05-03 19:13
Kinda new to Python here, and had no luck finding ready-made solutions, although I'm pretty sure there must be.

Could this be something?

```python
    def compare(a, b):
        def _compare(a, b, seen_a, seen_b, path):
            if id(a) in seen_a:
                return id(b) in seen_b and seen_a[id(a)] == seen_b[id(b)]
            seen_a[id(a)], seen_b[id(b)] = path, path
            if isinstance(a, dict):
                if not isinstance(b, dict):
                    return False
                return a.keys() == b.keys() and all([_compare(a.get(k), b.get(k), seen_a, seen_b, path + [k]) for k in b.keys()])
            if isinstance(a, list):
                if not isinstance(b, list):
                    return False
                return len(a)==len(b) and all(
                    [_compare(a[k], b[k], seen_a, seen_b, path + [k]) for k in range(len(b))])
            return a == b
        return _compare(a, b, {}, {}, [])
```

It seems to work for a few super-easy examples I made, and surprisingly for the test case you mentioned earlier.
It's hardly robust, and it would need its own tests, I suppose...

**Comment by simonrepp** [comment] 2019-05-04 11:49
Yes! Very very cool, really appreciate your pragmatic action. :)

I reviewed this and tried it out, not a python expert myself either, but I'd say you nailed it pretty much.
I only found one critical issue when trying to integrate it with the actual snapshot tests: All document elements (represented as dicts) are assigned a type, which comes from a constant (e.g. `FIELD = 'Field'` in the constants module and later `field['type'] = FIELD`), therefore all these type properties have the same `id()`. However when the snapshot is pulled in and deserialized from yaml, all these properties get different `id()`s because the yaml roundtrip loses the information that all these strings originally came from the same constant, therefore the test fails although the content is the same. Took some brainexercise to realize this, but now it's fixed (by only checking ids for dicts).

I agree with your assessment that this is not exactly robust, but even so it is an improvement to the current state and from my point of view we can go with it because there is indeed not much more complexity in the data structures than dicts, lists, strings, numbers and tuples (the latter never containing cyclic references so we don't need to handle them specifically).

Would you like to `git apply cyclic_dict_safe_comparison.diff.txt` the diff file below in your local checkout (possibly take a second look and feedback if you want :)) and submit a PR so the heavy lifting for this is properly attributed to you when it gets merged? :)

[cyclic_dict_safe_comparison.diff.txt](https://github.com/eno-lang/enolib/files/3144291/cyclic_dict_safe_comparison.diff.txt)

Thanks a lot, great initiative!

**Comment by mredaelli** [comment] 2019-05-04 12:40
Done - although I wouldn't be so sure mine was the heavy lifting :)

I only changed the default parameters on the inner function back to how they were before, because of [this](https://docs.quantifiedcode.com/python-anti-patterns/correctness/mutable_default_value_as_argument.html).

Next step for me would be having a way to modify the read data and write it back, so, basically, issue #1. I'd be happy work a bit on it, especially if you have the outline of an API or just pointers on how to integrate it in the existing classes.
Of the top of my head, I think it would be very cool to support automatic serialization of dataclasses, but not sure if it's reasonable.

**Comment by simonrepp** [comment] 2019-05-04 17:40
Thanks for the PR and correcting my anti-pattern, this in fact needed fixing [elsewhere too](https://github.com/eno-lang/enolib/commit/844a74c6729c2754becdb354c5dd3f1441300fde), glad you pointed it out here!

As for #1 I unfortunately don't have any API outlines worked out yet (if I had I'd likely have implemented the thing already hehe). The whole automatic serialization thing comes up a lot (understandably), but given eno's typelessness and general flexibility (which is also ambiguity when the coin is flipped around) this is a huge design task, and right now I can't really spend time on it because there's quite a backlog of important ecosystem duties I'd like to take care of first. (very prominently e.g. making the website not broken on mobile, publishing documentation for the new enolib ruby implementation, etc.). To reiterate on my answer in the issue itself - roll your own for the moment, gladly share your insights and if it fits well with the rest of the enolib and ecosystem plans in the backlog I'll gladly ask if we can integrate it in enolib at some point. ;)

**Closed** 2019-05-04 17:41 UTC
Labels: bug, good first issue, help wanted
